### ISSUE TITLE
Error running `serve`

### ISSUE THREAD

**Issue by NicWagenaar** [metriql/metriql#39]
I installed the Metriql CLI through docker: `docker pull buremba/metriql:latest`

Then, while in my dbt directory, ran the instructions on the installation page:
```
export DBT_PROJECT_DIR=${PWD}
export DBT_PROFILES_DIR=${HOME}/.dbt
export METRIQL_PORT=5656

docker run -it -p "${METRIQL_PORT}:5656" -v "${DBT_PROJECT_DIR}:/root/app" -v "${DBT_PROFILES_DIR}:/root/.dbt" -e METRIQL_RUN_HOST=0.0.0.0 -e DBT_PROJECT_DIR=/root/app buremba/metriql \
 serve
```

I then get the following error:
```
Nov 03, 2021 11:36:01 AM ru.yandex.clickhouse.ClickHouseDriver <clinit>
INFO: Driver registered
Exception in thread "main" java.lang.IllegalAccessError: class com.metriql.Commands$Serve tried to access private method 'java.lang.String com.metriql.Commands.getProfilesContent()' (com.metriql.Commands$Serve and com.metriql.Commands are in unnamed module of loader 'app')
	at com.metriql.Commands$Serve.access$getProfilesContent$s-537891160(Commands.kt:180)
	at com.metriql.Commands$Serve.run(Commands.kt:232)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
	at com.metriql.ServiceStarterKt.main(ServiceStarter.kt:25)
```

Any idea on how to resolve this?

**Comment by buremba** [comment]
Hey @NicWagenaar, you're right. It looks like our new [multi-tenant feature](https://metriql.com/metriql-cli/serve#multi-tenant-deployment) broke the single-tenant deployment. The fix is implemented, could you please download `metriql:latest` and try again?

**Comment by NicWagenaar** [comment]
Thanks @buremba. I pulled the latest version, but unfortunately I ran into a different error:
```
Nov 04, 2021 8:29:56 AM ru.yandex.clickhouse.ClickHouseDriver <clinit>
INFO: Driver registered
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Missing external type id property 'valueType'
 at [Source: (byte[])"{"metadata": {"dbt_schema_version": "https://schemas.getdbt.com/dbt/manifest/v3.json", "dbt_version": "0.21.0", "generated_at": "2021-11-03T13:11:22.653255Z", "invocation_id": "e415c5c2-4a11-4316-9299-4c983820a5ec", "env": {}, "project_id": "b750c393e2437fd9c212bd9a61a63336", "user_id": null, "send_anonymous_usage_stats": false, "adapter_type": "snowflake"}, "nodes": {"model.analytics.stg_opportunities": {"raw_sql": "select\n    -- Primary and foreign keys\n    id,\n    account_id,\n   "[truncated 424067 bytes]; line: 1, column: 4535] (through reference chain: com.metriql.dbt.DbtManifest["nodes"]->java.util.LinkedHashMap["model.analytics.outbound_opportunities"]->com.metriql.dbt.DbtManifest$Node["config"]->com.metriql.dbt.DbtManifest$Node$Config["meta"]->com.metriql.dbt.DbtManifest$Node$Meta["metriql"]->com.metriql.report.data.recipe.Recipe$RecipeModel["measures"]->java.util.LinkedHashMap["won_opportunities"]->com.metriql.report.data.recipe.Recipe$RecipeModel$Metric$RecipeMeasure["filters"]->java.util.ArrayList[0]->com.metriql.report.data.recipe.Recipe$RecipeModel$Metric$RecipeMeasure$Filter["operator"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportPropertyInputMismatch(DeserializationContext.java:1480)
	at com.fasterxml.jackson.databind.DeserializationContext.reportPropertyInputMismatch(DeserializationContext.java:1496)
	at com.fasterxml.jackson.databind.deser.impl.ExternalTypeHandler.complete(ExternalTypeHandler.java:273)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeUsingPropertyBasedWithExternalTypeId(BeanDeserializer.java:1004)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeWithExternalTypeId(BeanDeserializer.java:853)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:527)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:364)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:29)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4218)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3275)
	at com.metriql.dbt.DbtManifestParser.parse(DbtManifestParser.kt:36)
	at com.metriql.deployment.SingleTenantDeployment$Companion.parseRecipe(SingleTenantDeployment.kt:173)
	at com.metriql.deployment.SingleTenantDeployment$Companion.parseRecipe$default(SingleTenantDeployment.kt:136)
	at com.metriql.deployment.SingleTenantDeployment$modelService$1.invoke(SingleTenantDeployment.kt:49)
	at com.metriql.deployment.SingleTenantDeployment$modelService$1.invoke(SingleTenantDeployment.kt:47)
	at com.metriql.service.model.UpdatableModelService.<init>(UpdatableModelService.kt:8)
	at com.metriql.deployment.SingleTenantDeployment.<init>(SingleTenantDeployment.kt:47)
	at com.metriql.Commands$Serve.run(Commands.kt:232)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
	at com.metriql.ServiceStarterKt.main(ServiceStarter.kt:25)
```

Does this have something to do with my configuration?

**Comment by buremba** [comment]
@NicWagenaar it looks like the manifest.json file is versioned as `v3`. Do you mind sharing the `manifest.json` with me so that I can try to reproduce it on my end?

**Comment by NicWagenaar** [comment]
@buremba I've replicated the error in a fresh jaffle_shop project. Put the manifest for it in a gist here: https://gist.github.com/NicWagenaar/56a81670917c939a84cd0552abf5ed95

**Comment by buremba** [comment]
@NicWagenaar good catch. It looks like the error was because `status` dimension doesn't have a type defined in the yml file and the value type is not defined for the dimension: If you add the following `valueType` property, it should work:

<img width="352" alt="CleanShot 2021-11-05 at 03 04 04@2x" src="https://user-images.githubusercontent.com/82745/140436937-edda1885-6006-485d-ab93-af9e9db59e31.png">

I'm aware that it's not convenient enough, it's rather a workaround. I will keep this issue open until I find a better solution. Different field types have different `operator`s so the system needs to know the field type in order to construct the SQL expression in a proper way. 
If you don't define the [type](https://metriql.com/reference/field#type), the system can automatically infer the type by running a metadata query and let you use the [appropriate operators](https://metriql.com/query/introduction#operator) automatically. Does that make sense?

**Comment by NicWagenaar** [comment]
@buremba Makes a lot of sense, thanks for looking into this!
