### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by AndreasTA-AW** [metriql/metriql#51]
Not really sure where this is coming from, but when using thoughtspot / DBeaver these errors pop up a lot in the metriql logs.
```
SEVERE: An uncaught exception raised while processing request.
java.util.ConcurrentModificationException
        at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
        at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source)
        at java.base/java.util.LinkedHashMap$LinkedEntryIterator.next(Unknown Source)
        at com.metriql.service.task.TaskQueueService.currentTasks(TaskQueueService.kt:155)
        at com.metriql.service.task.TaskQueueService.currentTasks$default(TaskQueueService.kt:75)
        at com.metriql.service.task.TaskHttpService.activeCount(TaskHttpService.kt:40)
        at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
        at org.rakam.server.http.HttpServer.handleJsonRequest(HttpServer.java:622)
        at org.rakam.server.http.HttpServer.lambda$createGetRequestHandler$18(HttpServer.java:506)
        at org.rakam.server.http.RouteMatcher.handle(RouteMatcher.java:47)
        at org.rakam.server.http.HttpServerHandler.channelRead(HttpServerHandler.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:883)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:389)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.base/java.lang.Thread.run(Unknown Source)
        
```

**Comment by buremba** [comment]
Thanks for reporting the bug!
