### ISSUE TITLE
Floats / Decimals

### ISSUE THREAD

**Issue by AndreasTA-AW** [metriql/metriql#58]
Hi,
When I'm using dbeaver and testing to do some calculations or just retrieving decimals/floats I get the below error.
One weird thing is that it says "type":"unknown" in the response, which makes me think it's something weird with the types.

```
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error: Error executing query
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:513)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:444)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:431)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:816)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3468)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:171)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4810)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.sql.SQLException: Error executing query
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:287)
	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)
	... 12 more
Caused by: java.lang.RuntimeException: Error fetching next at http://localhost:5656/v1/statement/queued/?id=e8a50b5b-ea33-476e-b23d-f8ebb37fce2a returned an invalid response: JsonResponse{statusCode=200, statusMessage=OK, headers={access-control-allow-origin=[*], connection=[keep-alive], content-length=[1898], content-type=[application/json]}, hasValue=false} [Error: {"id":"e8a50b5b-ea33-476e-b23d-f8ebb37fce2a","infoUri":"http://localhost:5656/v1/statement/queued/?id=e8a50b5b-ea33-476e-b23d-f8ebb37fce2a","nextUri":"http://localhost:5656/v1/statement/queued/?id=e8a50b5b-ea33-476e-b23d-f8ebb37fce2a","columns":[{"name":"column","type":"unknown","typeSignature":{"rawType":"unknown","arguments":[]}}],"data":[["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"]],"stats":{"state":"QUEUED","queued":true,"scheduled":false,"nodes":0,"totalSplits":1,"queuedSplits":0,"runningSplits":0,"completedSplits":0,"cpuTimeMillis":0,"wallTimeMillis":0,"queuedTimeMillis":2702,"elapsedTimeMillis":2702,"processedRows":0,"processedBytes":0,"physicalInputBytes":0,"peakMemoryBytes":0,"spilledBytes":0},"warnings":[]}]
	at io.trino.jdbc.$internal.client.StatementClientV1.requestFailedException(StatementClientV1.java:447)
	at io.trino.jdbc.$internal.client.StatementClientV1.advance(StatementClientV1.java:386)
	at io.trino.jdbc.TrinoResultSet.getColumns(TrinoResultSet.java:235)
	at io.trino.jdbc.TrinoResultSet.create(TrinoResultSet.java:53)
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:262)
	... 15 more
Caused by: java.lang.IllegalArgumentException: Unable to create class io.trino.jdbc.$internal.client.QueryResults from JSON response:
[{"id":"e8a50b5b-ea33-476e-b23d-f8ebb37fce2a","infoUri":"http://localhost:5656/v1/statement/queued/?id=e8a50b5b-ea33-476e-b23d-f8ebb37fce2a","nextUri":"http://localhost:5656/v1/statement/queued/?id=e8a50b5b-ea33-476e-b23d-f8ebb37fce2a","columns":[{"name":"column","type":"unknown","typeSignature":{"rawType":"unknown","arguments":[]}}],"data":[["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"]],"stats":{"state":"QUEUED","queued":true,"scheduled":false,"nodes":0,"totalSplits":1,"queuedSplits":0,"runningSplits":0,"completedSplits":0,"cpuTimeMillis":0,"wallTimeMillis":0,"queuedTimeMillis":2702,"elapsedTimeMillis":2702,"processedRows":0,"processedBytes":0,"physicalInputBytes":0,"peakMemoryBytes":0,"spilledBytes":0},"warnings":[]}]
	at io.trino.jdbc.$internal.client.JsonResponse.<init>(JsonResponse.java:69)
	at io.trino.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:143)
	at io.trino.jdbc.$internal.client.StatementClientV1.advance(StatementClientV1.java:372)
	... 18 more
Caused by: io.trino.jdbc.$internal.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `io.trino.jdbc.$internal.client.QueryResults`, problem: Illegal base64 character 2e
 at [Source: (String)"{"id":"e8a50b5b-ea33-476e-b23d-f8ebb37fce2a","infoUri":"http://localhost:5656/v1/statement/queued/?id=e8a50b5b-ea33-476e-b23d-f8ebb37fce2a","nextUri":"http://localhost:5656/v1/statement/queued/?id=e8a50b5b-ea33-476e-b23d-f8ebb37fce2a","columns":[{"name":"column","type":"unknown","typeSignature":{"rawType":"unknown","arguments":[]}}],"data":[["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0.8"],["0.8"],["0.8"],["0.3"],["0.8"],["0."[truncated 1398 chars]; line: 1, column: 1898]
	at io.trino.jdbc.$internal.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
	at io.trino.jdbc.$internal.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1907)
	at io.trino.jdbc.$internal.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:587)
	at io.trino.jdbc.$internal.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:610)
	at io.trino.jdbc.$internal.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:293)
	at io.trino.jdbc.$internal.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:288)
	at io.trino.jdbc.$internal.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
	at io.trino.jdbc.$internal.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:520)
	at io.trino.jdbc.$internal.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at io.trino.jdbc.$internal.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:362)
	at io.trino.jdbc.$internal.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:195)
	at io.trino.jdbc.$internal.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
	at io.trino.jdbc.$internal.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2033)
	at io.trino.jdbc.$internal.jackson.databind.ObjectReader.readValue(ObjectReader.java:1491)
	at io.trino.jdbc.$internal.client.JsonCodec.fromJson(JsonCodec.java:68)
	at io.trino.jdbc.$internal.client.JsonResponse.<init>(JsonResponse.java:66)
	... 20 more
Caused by: java.lang.IllegalArgumentException: Illegal base64 character 2e
	at java.base/java.util.Base64$Decoder.decode0(Unknown Source)
	at java.base/java.util.Base64$Decoder.decode(Unknown Source)
	at java.base/java.util.Base64$Decoder.decode(Unknown Source)
	at io.trino.jdbc.$internal.client.FixJsonDataUtils.fixValue(FixJsonDataUtils.java:187)
	at io.trino.jdbc.$internal.client.FixJsonDataUtils.fixData(FixJsonDataUtils.java:74)
	at io.trino.jdbc.$internal.client.QueryResults.<init>(QueryResults.java:69)
	at jdk.internal.reflect.GeneratedConstructorAccessor24.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at io.trino.jdbc.$internal.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at io.trino.jdbc.$internal.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:291)
	... 31 more
```

The dimension is specified like this:

```yml
- name: column
   meta:
      metriql.dimension:
         type: float # ( Tested decimal as well )
```

**Comment by AndreasTA-AW** [comment]
The types are "BIGNUMERIC" in BigQuery, if I look in the code it feels like this type is not supported?

**Comment by buremba** [comment]
It looks like BIGNUMERIC is interpreted as STRING which causes SQL clients to fail. Fixed the issue, thanks for reporting!
