### ISSUE TITLE
Pass credentials to datasource

### ISSUE THREAD

**Issue by lmabraidofandino** [metriql/metriql#69]
We're running Metriql within a docker container using this command:
sudo docker run -it -p "5656:5656" -v "${DBT_PROJECT_DIR}:/root/app" -v "${DBT_PROFILES_DIR}:/root/.dbt" -e METRIQL_RUN_HOST=0.0.0.0 -e DBT_PROJECT_DIR=/root/app buremba/metriql serve --pass-credentials-to-datasource
Exception in thread "main" java.lang.NullPointerException
       at com.metriql.deployment.SingleTenantDeployment.getDataSource(SingleTenantDeployment.kt:75)
       at com.metriql.deployment.SingleTenantDeployment$modelService$1.invoke(SingleTenantDeployment.kt:47)
       at com.metriql.deployment.SingleTenantDeployment$modelService$1.invoke(SingleTenantDeployment.kt:46)
       at com.metriql.service.model.UpdatableModelService.<init>(UpdatableModelService.kt:8)
       at com.metriql.deployment.SingleTenantDeployment.<init>(SingleTenantDeployment.kt:46)
       at com.metriql.Commands$Serve.run(Commands.kt:233)
       at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
       at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
       at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
       at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
       at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
       at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
       at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
       at com.metriql.ServiceStarterKt.main(ServiceStarter.kt:10)
Note that it's getting a NullPointerException.  How can we pass credentials to the datasource?  Thanks!

**Comment by buremba** [comment]
Hey there, there was a bug for the `pass-credentials-to-datasource` feature which is now fixed. Can you please try the latest version and let me know how it goes?

**Comment by buremba** [comment]
Sorry for missing your message, it was fixed the day that you answered the question. :)

**Comment by lmabraidofandino** [comment]
I just confirmed that on an AWS EC2 instance, **docker pull buremba/metriql:latest** and **docker run -it -p "${METRIQL_PORT}:5656" -v "${DBT_PROJECT_DIR}:/root/app" -v "${DBT_PROFILES_DIR}:/root/.dbt" -e METRIQL_RUN_HOST=0.0.0.0 -e DBT_PROJECT_DIR=/root/app buremba/metriql \
 serve** work correctly.  I am able to use DBeaver to view the metriql data without getting **SQL Error: Authentication failed: Unauthorized**.

**Comment by buremba** [comment]
Thanks for letting me know!
