### ISSUE TITLE
Unknown data type: Array(String)

### ISSUE THREAD

**Issue by oev81** [metriql/metriql#78]
Bug with array types in Сlickhouse.
Seems like the problem appeared in #65
Revision [daad675147c77eda82e46103be712a3af7ac6c47](https://github.com/metriql/metriql/commit/daad675147c77eda82e46103be712a3af7ac6c47) works. 

```
Mar 29, 2022 7:51:12 AM com.metriql.dbt.DbtManifestParser parse
INFO: Parsing 396 nodes, 133 sources and 0 metrics
Mar 29, 2022 7:51:12 AM io.airlift.log.Logger error
SEVERE: Error while processing request
java.lang.IllegalArgumentException: Unknown data type: Array(String)
	at com.clickhouse.client.ClickHouseDataType.of(ClickHouseDataType.java:187)
	at com.metriql.warehouse.clickhouse.ClickhouseDataSource.getFieldType(ClickhouseDataSource.kt:74)
	at com.metriql.warehouse.JDBCWarehouse.readResultSetForMetadata(JDBCWarehouse.kt:107)
	at com.metriql.warehouse.JDBCWarehouse.getTable(JDBCWarehouse.kt:184)
	at com.metriql.dbt.DbtManifest$Node.toModel(DbtManifest.kt:209)
	at com.metriql.dbt.DbtManifestParser.parse(DbtManifestParser.kt:54)
	at com.metriql.deployment.SingleTenantDeployment$Companion.parseRecipe(SingleTenantDeployment.kt:171)
	at com.metriql.deployment.SingleTenantDeployment$Companion.parseRecipe$default(SingleTenantDeployment.kt:134)
	at com.metriql.deployment.MultiTenantDeployment.getAuth(MultiTenantDeployment.kt:66)
	at com.metriql.MetriqlAuthRequestParameterFactory.create$lambda-0(MetriqlAuthRequestParameterFactory.kt:68)
	at org.rakam.server.http.HttpServer.lambda$createGetRequestHandler$18(HttpServer.java:486)
	at org.rakam.server.http.RouteMatcher.handle(RouteMatcher.java:47)
	at org.rakam.server.http.HttpServerHandler.channelRead(HttpServerHandler.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:883)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:389)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by buremba** [comment]
Thanks for reporting the bug. Can you please try if it's working in latest?
