### ISSUE TITLE
Does not support count_distinct dbt metric type

### ISSUE THREAD

**Issue by mjirv** [metriql/metriql#81]
To replicate, define a metric with `type: count_distinct`.

For example:
```yaml
  - name: customers_with_orders
    label: Customers
    model: ref('orders')
    description: The number of customers we have

    type: count_distinct
    sql: customer_id

    timestamp: order_date
    time_grains: [day, week, month, quarter, year]

    dimensions:
      - status
```

Running `metriql serve` gives the following output:
```
Exception in thread "main" com.metriql.dbt.DbtYamlParser$ParseException: (metrics.metric.dbt_demo_project.customers_with_orders.type, Invalid value, cannot parse token `FIELD_NAME` for target null)
        at com.metriql.dbt.DbtManifestParser.parse(DbtManifestParser.kt:42)
        at com.metriql.deployment.SingleTenantDeployment$Companion.parseRecipe(SingleTenantDeployment.kt:171)
        at com.metriql.deployment.SingleTenantDeployment$Companion.parseRecipe$default(SingleTenantDeployment.kt:134)
        at com.metriql.deployment.SingleTenantDeployment$modelService$1.invoke(SingleTenantDeployment.kt:49)
        at com.metriql.deployment.SingleTenantDeployment$modelService$1.invoke(SingleTenantDeployment.kt:47)
        at com.metriql.service.model.UpdatableDatasetService.<init>(UpdatableDatasetService.kt:8)
        at com.metriql.deployment.SingleTenantDeployment.<init>(SingleTenantDeployment.kt:47)
        at com.metriql.Commands$Serve.run(Commands.kt:233)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
        at com.metriql.ServiceStarterKt.main(ServiceStarter.kt:10)
```

This can be "fixed" by changing the dbt metric so the type is `count_unique` which I believe is a valid metriql type but not a valid dbt metric type.

**Comment by buremba** [comment]
Metriql now supports `count_distinct` since it's explicitly mentioned in dbt Docs but unfortunately, AFAIK dbt doesn't really have a set of dbt metric types, it's just an example in the docs but it can be any kind of string. Please correct me if I'm wroing.

**Comment by mjirv** [comment]
Yeah they don't have it documented well. The best source of truth I know of is [this if statement](https://github.com/dbt-labs/dbt_metrics/blob/a9d0feec7165303b1d16c30714eb601a55143b66/macros/aggregate_primary_metric.sql#L8), lol

**Comment by buremba** [comment]
Yeah, that's a good start. They will probably support them in the upcoming products which will be part of dbt Cloud but for now Metriql already supports these aggregations. :)
