### ISSUE TITLE
profiles.yml does not exist in /root/.dbt/profiles.yml

### ISSUE THREAD

**Issue by eponkratova** [metriql/metriql#97]
Good day,

I am using GitBash and run:
export DBT_PROJECT_DIR=${PWD}
export DBT_PROFILES_DIR=${HOME}/.dbt
export METRIQL_PORT=5656

Then, I run  docker run -it -p "${METRIQL_PORT}:5656" -v "${DBT_PROJECT_DIR}:/root/app" -v "${DBT_PROFILES_DIR}:/root/.dbt" -e METRIQL_RUN_HOST=0.0.0.0 -e DBT_PROJECT_DIR=/root/app buremba/metriql:0.7 --profiles-dir ~/.dbt serve

But got:

$  docker run -it -p "${METRIQL_PORT}:5656" -v "${DBT_PROJECT_DIR}:/root/app" -v "${DBT_PROFILES_DIR}:/root/.dbt" -e METRIQL_RUN_HOST=0.0.0.0 -e DBT_PROJECT_DIR=/root/app buremba/metriql:0.7 --profiles-dir ~/.dbt serve
Exception in thread "main" java.lang.IllegalArgumentException: profiles.yml does not exist in /root/.dbt/profiles.yml. Please set --profiles-dir option.
        at com.metriql.deployment.SingleTenantDeployment$Companion.getProfileConfigForSingleTenant(SingleTenantDeployment.kt:92)
        at com.metriql.deployment.SingleTenantDeployment.<init>(SingleTenantDeployment.kt:45)
        at com.metriql.Commands$Serve.run(Commands.kt:233)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
        at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
        at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:395)
        at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:392)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:410)
        at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:435)
        at com.metriql.ServiceStarterKt.main(ServiceStarter.kt:10)

dbt profiles is in the default location. What am I missing? As I understood, --profiles-dir is to be used when the location of the dbt profile is different from the default one.

**Comment by eponkratova** [comment]
Resolved. If you are on Windows and use bash, run:
winpty docker run -it -p "${METRIQL_PORT}:5656" -v "/${DBT_PROJECT_DIR}://root/app" -v "/${DBT_PROFILES_DIR}://root/dbt" -e METRIQL_RUN_HOST=0.0.0.0 -e DBT_PROJECT_DIR=//root/app buremba/metriql serve
